[package]
name = "dro_map_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.23.0"
egui_extras = { version = "0.23.0", features = ["image"]}
eframe = "0.23.0"
env_logger = "0.10.0"